---
# tasks file for dhcpd
- name: install dhcpd(Ubuntu)
  apt:
   name: isc-dhcp-server
   state: latest
   update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: install dhcpd(CentOS)
  dnf:
   name: dhcp-server
   state: latest
   update_cache: yes
  when: ansible_distribution == "CentOS"
