---
# tasks file for bind9
- name: install bind9 for Ubuntu
  apt:
   name: bind
   state: latest
   update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: install bind9 for CentOS
  dnf:
   name: bind
   state: latest
   update_cache: yes
  when: ansible_distribution == "CentOS"
