---
# tasks file for maria_db
- name: install mariadb server package(CentOS)
  tags: centos, db, mariadb
  dnf:
   name: mariadb
   state: latest
  when: ansible_distribution == "centOS"

- name: install mariadb server package(Ubuntu)
  tags: ubuntu, db, mariadb
  apt:
   name: mariadb-server
   state: latest
   when: ansible_distrubution == "Ubuntu"
