---
# tasks file for httpd
- name: install httpd for Ubuntu
  apt:
   name: httpd
   state: latest
   update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: install httpd for CentOS
  dnf:
   name: httpd
   state: latest
   update_cache: yes
  when: ansible_distribution == "CentOS"
