---
# tasks file for vsftpd
- name: install vsftpd for Ubuntu
  apt:
   name: vsftpd
   state: latest
  when: ansible_distribution == "Ubuntu"

- name: install vsftpd for CentOS
  dnf:
   name: vsftpd
   state: latest
  when: ansible_distribution == "CentOS"
